# Generated by Django 4.2.1 on 2023-07-20 00:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.CharField(max_length=10)),
                ('time', models.DurationField(default=datetime.timedelta(days=1))),
            ],
        ),
        migrations.CreateModel(
            name='EmailTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('time', models.TimeField(default=datetime.time(0, 0))),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('freq', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.frequency')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
