# Generated by Django 4.2.1 on 2023-06-18 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Frequency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("freq", models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name="emailtime",
            name="freq",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.frequency"
            ),
        ),
    ]
