# Generated by Django 4.2.1 on 2023-06-08 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="preference",
            old_name="preference",
            new_name="text",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
