# Generated by Django 4.2.1 on 2023-06-20 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_combinedtext_id_alter_combinedtext_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CombinedText',
        ),
    ]
