# Generated by Django 4.2.1 on 2023-06-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_article_userarticle_article_unique_article_journal_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userarticle',
            name='unique_user_article_journal',
        ),
        migrations.RemoveField(
            model_name='userarticle',
            name='journal_id',
        ),
        migrations.AddConstraint(
            model_name='userarticle',
            constraint=models.UniqueConstraint(fields=('user', 'article'), name='unique_user_article_journal'),
        ),
    ]
