# Generated by Django 4.2.1 on 2023-06-20 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_rename_preference_preference_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combined_text', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_texts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
