# Generated by Django 4.2.1 on 2023-06-20 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_combinedtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combinedtext',
            name='id',
        ),
        migrations.AlterField(
            model_name='combinedtext',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='combined_text', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
