# Generated by Django 4.2.1 on 2023-06-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_remove_userarticle_unique_user_article_journal_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalArticle",
            fields=[
                ("title", models.CharField(max_length=255)),
                ("publication_title", models.CharField(max_length=255)),
                (
                    "item_doi",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("authors", models.CharField(max_length=255)),
                ("publication_year", models.PositiveIntegerField()),
                ("url", models.URLField()),
                ("keywords", models.CharField(max_length=255)),
                ("language", models.CharField(max_length=255)),
            ],
        ),
    ]
