# Generated by Django 4.2.1 on 2023-06-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_remove_userarticle_unique_user_article_journal_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalArticle",
            fields=[
                ("article_index", models.IntegerField(default=-1)),
                ("publication_index", models.IntegerField(default=-1)),
                ("item_doi", models.CharField(primary_key=True, serialize=False)),
                ("publication_year", models.PositiveIntegerField(null=True)),
                ("url", models.URLField()),
                ("article_tags", models.CharField(null=True)),
            ],
        ),
    ]
