# Generated by Django 4.2.1 on 2023-06-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_journalarticle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalarticle",
            name="authors",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="journalarticle",
            name="item_doi",
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="journalarticle",
            name="keywords",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="journalarticle",
            name="language",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="journalarticle",
            name="publication_title",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="journalarticle",
            name="title",
            field=models.CharField(),
        ),
    ]
