# Generated by Django 4.2.1 on 2023-06-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_alter_journalarticle_authors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalarticle",
            name="authors",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="journalarticle",
            name="keywords",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="journalarticle",
            name="language",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="journalarticle",
            name="publication_title",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="journalarticle",
            name="publication_year",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="journalarticle",
            name="title",
            field=models.CharField(null=True),
        ),
    ]
