# Generated by Django 4.2.1 on 2023-06-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtime',
            name='freq',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
