# Generated by Django 4.2.1 on 2023-06-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailtime_freq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtime',
            name='pref',
        ),
    ]
